# Generated by Django 4.0.4 on 2022-05-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1)),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opus.opus')),
            ],
        ),
    ]
