# Generated by Django 4.0.4 on 2022-05-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_quote_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertag',
            options={'verbose_name': 'Тег персонажа', 'verbose_name_plural': 'Теги персонажа'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
    ]
