# Generated by Django 4.0.4 on 2022-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_charactertag_options_alter_quote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
    ]
