# Generated by Django 4.0.4 on 2022-05-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0005_alter_author_birth_date_alter_author_death_date_and_more'),
        ('characters', '0006_alter_character_options_alter_character_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opus.opus', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='charactertag',
            name='label',
            field=models.CharField(max_length=32, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='Источник цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
