# Generated by Django 4.0.4 on 2022-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
