# Generated by Django 4.0.4 on 2022-05-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0002_alter_author_birth_date_alter_author_death_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
