# Generated by Django 4.0.4 on 2022-05-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0003_alter_author_birth_date_alter_author_death_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='opus',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
