# Generated by Django 4.0.4 on 2022-05-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0004_quote_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_answers', models.ManyToManyField(to='characters.character')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.quote')),
            ],
        ),
    ]
