# Generated by Django 4.0.4 on 2022-06-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_answers', models.ManyToManyField(to='writings.character', verbose_name='Дополнительные ответы')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writings.quote', verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Вопрос теста по цитатам',
                'verbose_name_plural': 'Вопросы теста по цитатам',
            },
        ),
    ]
