# Generated by Django 4.0.4 on 2022-05-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotequestion',
            options={'verbose_name': 'Вопрос теста по цитатам', 'verbose_name_plural': 'Вопросы теста по цитатам'},
        ),
    ]
