# Generated by Django 4.0.4 on 2022-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_quotestestrun_finish_time_quotestestrun_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotestestrun',
            options={'verbose_name': 'Тест на знание цитат'},
        ),
    ]
